version: "3.8"
services:

  service-discovery:
    build: apps/service-discovery
    image: bsuir-hrm-dataanlyzer-service-discovery
    ports:
      - "8761:8761"
      - "5555"
    environment:
      - JAVA_TOOL_OPTIONS=${DEBUG_OPTIONS}
    restart: always

  data-extractor:
    build: apps/data-extractor
    image: bsuir-hrm-dataanlyzer-data-extractor
    ports:
      - "8080:8080"
      - "5555"
    environment:
      - JAVA_TOOL_OPTIONS=${DEBUG_OPTIONS}
    depends_on:
      - service-discovery
    restart: always

  service-product:
    build: apps/service-product
    image: bsuir-hrm-dataanlyzer-service-product
    ports:
      - "8081:8080"
      - "5555"
    environment:
      - JAVA_TOOL_OPTIONS=${DEBUG_OPTIONS}
    depends_on:
      - service-discovery
      - data-extractor
    restart: always

  service-processing:
    build: apps/service-processing
    image: bsuir-hrm-dataanlyzer-service-processing
    ports:
      - "8082:8080"
      - "5555"
    environment:
      - JAVA_TOOL_OPTIONS=${DEBUG_OPTIONS}
    depends_on:
      - service-discovery
      - service-product
    restart: always

  service-desktop:
    build: apps/service-desktop
    image: bsuir-hrm-dataanlyzer-service-desktop
    ports:
      - "8083:8080"
      - "5555"
    environment:
      - JAVA_TOOL_OPTIONS=${DEBUG_OPTIONS}
    depends_on:
      - service-discovery
    restart: always
