spring:
  application:
    name: data-extractor
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
hrm:
  api:
    prices:
      date-pattern: yyyy-MM
      url: https://catalog.api.onliner.by/products/
    products:
      url: https://catalog.onliner.by/sdapi/catalog.api/search/
logging:
  level:
    com:
      bsuir:
        hrm: trace
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
