spring:
  application:
    name: service-product
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  h2:
    console:
      enabled: 'true'
      path: /h2-console
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
logging:
  level:
    com:
      bsuir:
        hrm: trace
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/tech_market_analyzer
    password: root
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    com:
      bsuir:
        hrm: debug
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tech_market_analyzer
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: 'false'
logging:
  level:
    com:
      bsuir:
        hrm: warn
