scrape_configs:
  - job_name: 'data-extractor'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'data-extractor:8080' ]

  - job_name: 'service-desktop'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-desktop:8080' ]

  - job_name: 'service-discovery'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-discovery:8761' ]

  - job_name: 'service-gateway'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-gateway:8080' ]

  - job_name: 'service-processing'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-processing:8080' ]

  - job_name: 'service-product'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-product:8080' ]

  - job_name: 'service-tenant'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-tenant:8080' ]
