spring:
  application:
    name: service-desktop
logging:
  level:
    com:
      bsuir:
        hrm: trace
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
