spring:
  application:
    name: service-processing
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
logging:
  level:
    com:
      bsuir:
        hrm: trace
